Dataset Online Retail II UCI: https://www.kaggle.com/datasets/mashlyn/online-retail-ii-uci/data

## Data Understanding

Dataset ini berisi semua transaksi yang terjadi di sebuah perusahaan ritel online yang berbasis di Inggris dan terdaftar secara resmi, yang tidak memiliki toko fisik (hanya berjualan online). Transaksi tersebut terjadi antara tanggal 1 Desember 2009 hingga 9 Desember 2011.

Berikut adalah rincian kolom-kolomnya:
* Invoice: Nomor faktur unik untuk setiap transaksi. Jika nomor ini diawali dengan 'C', itu menunjukkan pembatalan pesanan (cancellation).
* StockCode: Kode unik untuk setiap produk (item).
* Description: Nama atau deskripsi produk.
* Quantity: Jumlah produk yang dibeli dalam satu transaksi. Nilai negatif menunjukkan pengembalian barang.
* InvoiceDate: Tanggal dan waktu ketika transaksi (faktur) dibuat.
* Price: Harga satuan produk dalam poundsterling
* Customer ID: ID unik untuk setiap pelanggan. Nilai kosong (NaN) menunjukkan bahwa pelanggan tidak terdaftar atau transaksi dilakukan oleh tamu.
* Country: Negara tempat pelanggan berada.

Data Overview:  

- Data memiliki Baris: 1067371 dan Kolom:8
- Data memiliki 3 jenis kolom: string(5), integer(1), float(2)
- `Invoice` yang dimulai dengan 'C' perlu dibersihkan karena transaksinya dibatalkan
- Cek nilai negatif pada kolom `Quantity` dan `Price`

**Goals for RFM Analysis
Customer Segmentation (RFM Analysis)**
  
  khusus untuk Member (Hanya Transaksi yang terdapat CustomerID)

1. **Customer Segmentation (RFM Analysis)**:
   * Gunakan metrik Recency, Frequency, dan Monetary untuk mengelompokkan pelanggan ke dalam beberapa segmen (misalnya: Champions, At Risk, Potential Loyalists).
   * Identifikasi pelanggan bernilai tinggi serta pelanggan yang membutuhkan strategi reaktivasi.

2. **Customer Behavior Analysis**:
   * Analisis pola pembelian pelanggan berdasarkan frekuensi transaksi dan total pengeluaran.
   * Tentukan pelanggan yang paling sering berbelanja dan pelanggan yang sudah lama tidak bertransaksi untuk strategi retensi.

3. **Product Performance Insights**:
   * Analisis hubungan antara segmen pelanggan dan produk yang mereka beli untuk mengoptimalkan strategi penjualan.
   * Evaluasi produk yang sering dibeli oleh pelanggan bernilai tinggi agar dapat dijadikan fokus dalam promosi.

4. **Optimization Recommendations**:
   * Rekomendasikan kampanye pemasaran yang ditargetkan untuk masing-masing segmen pelanggan (misalnya: program loyalitas untuk Champions, diskon untuk At Risk).
   * Strategi upselling dan cross-selling berdasarkan preferensi pelanggan dari analisis RFM.

# Import Library

In [ ]:
# Memanggil library yang diperlukan
import pandas as pd
import numpy as np
import seaborn as sns
import warnings
import matplotlib.pyplot as plt
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

# Load Dataset

In [ ]:
df = pd.read_csv('online_retail_II.csv')
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1067371 entries, 0 to 1067370
Data columns (total 8 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   Invoice      1067371 non-null  object
 1   StockCode    1067371 non-null  object
 2   Description  1062989 non-null  object
 3   Quantity     1067371 non-null  int64
 4   InvoiceDate  1067371 non-null  object
 5   Price        1067371 non-null  float64
 6   Customer ID  824364 non-null   float64
 7   Country      1067371 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 65.1+ MB

Ada 243.007 baris nilai yang hilang di kolom Customer ID

In [ ]:
# Menampilkan jumlah data unik
print("\n=== Cek Data Unik ===")
print(df.nunique())

=== Cek Data Unik ===
Invoice        53628
StockCode       5305
Description     5698
Quantity        1057
InvoiceDate    47635
Price           2807
Customer ID     5942
Country           43
dtype: int64

# Data Cleaning

# `Cek Missing Value`

In [ ]:
from IPython.display import display

# Cek Missing Value
print("Missing Value di Setiap Kolom:")
display(df.isnull().sum().to_frame(name="Missing Values"))

# Menghitung keseluruhan data tanpa missing value
def missing(dataset, key):
    tanpa_null = pd.DataFrame(len(dataset[key]) - dataset.isnull().sum(), columns=['Data Count'])
    percentage_null = pd.DataFrame((len(dataset[key]) - (len(dataset[key]) - dataset.isnull().sum())) / len(dataset[key]) * 100, columns=['Percentage'])
    percentage_null = percentage_null.round(2)

    # Menampilkan jumlah data tanpa missing value
    print("\nJumlah Data Tanpa Missing Value:")
    display(tanpa_null)

    # Menampilkan persentase nilai yang hilang
    print("\nPersentase Missing Value:")
    display(percentage_null)

    return tanpa_null, percentage_null

# Memanggil fungsi dan menampilkan hasilnya
tanpa_null, percentage_null = missing(df, 'Invoice')

Missing Value di Setiap Kolom:

             Missing Values
Invoice                   0
StockCode                 0
Description            4382
Quantity                  0
InvoiceDate               0
Price                     0
Customer ID          243007
Country                   0

Jumlah Data Tanpa Missing Value:

             Data Count
Invoice         1067371
StockCode       1067371
Description     1062989
Quantity        1067371
InvoiceDate     1067371
Price           1067371
Customer ID      824364
Country         1067371

Persentase Missing Value:

             Percentage
Invoice            0.00
StockCode          0.00
Description        0.41
Quantity           0.00
InvoiceDate        0.00
Price              0.00
Customer ID       22.77
Country            0.00

# `Handling Missing Value`

Missing value akan di drop, karena bertujuan untuk RFM yang berfokus pada transaksi yang memiliki `CustomerID`

In [ ]:
#  Removing NaN's in Customer ID
print("Shape data sebelum menghapus NaN di CustomerID",df.shape)
df.dropna(subset="Customer ID",axis=0,inplace=True)
print("Shape data setelah menghapus NaN di CustomerID",df.shape)

Shape data sebelum menghapus NaN di CustomerID (1067371, 8)
Shape data setelah menghapus NaN di CustomerID (824364, 8)

In [ ]:
# Cek Missing Value setelah di handling
print("Missing values di setiap kolom setelah cleaning customerID :\n\n", df.isnull().sum())

Missing values di setiap kolom setelah cleaning customerID :

 Invoice        0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
Price          0
Customer ID    0
Country        0
dtype: int64

- Data sudah tidak ada Missing Value.   
- NaN dari kolom `Description` juga selaras dengan `CustomerID` yang hilang/dihapus

### Menghapus transaksi yang dibatalkan dari Invoice

karena ada 2 tipe Invoice yaitu yang berawalan dengan "C" dan Tidak  
- berawalan C: Transaksi yang dibatalkan
- tanpa awalan C : Transaksi yang selesai

In [ ]:
# Melihat keseluruhan data Invoice
print(df[['Invoice']].to_string(index=False))

Output hidden; open in https://colab.research.google.com to view.

In [ ]:
# Melihat jumlah Invoice dengan awalan 'C' dan tanpa 'C'
cancelled_count = df[df['Invoice'].astype(str).str.startswith('C')]['Invoice'].count()
non_cancelled_count = df[~df['Invoice'].astype(str).str.startswith('C')]['Invoice'].count()

invoice_counts = pd.DataFrame({
"Invoice Type": ["Cancelled (C)", "Non-Cancelled"],
    "Count": [cancelled_count, non_cancelled_count]
})

print(invoice_counts.to_string(index=False))

 Invoice Type  Count
Cancelled (C)  18744
Non-Cancelled 805620

Filter (Memilah) invoice tanpa awalan C

In [ ]:
# menggunakan operator (~) dapat memilih seluruh data di kolom Invoice column yang tidak mengandung "C".
df = df[~df.Invoice.str.contains('C',na=False)]
print("Data sudah bersih dari transaksi yang dibatalkan (berawalan C)")

Data sudah bersih dari transaksi yang dibatalkan (berawalan C)

In [ ]:
cancelled_count = df[df['Invoice'].astype(str).str.startswith('C')]['Invoice'].count()
non_cancelled_count = df[~df['Invoice'].astype(str).str.startswith('C')]['Invoice'].count()

invoice_counts = pd.DataFrame({
"Invoice Type": ["Cancelled (C)", "Non-Cancelled"],
    "Count": [cancelled_count, non_cancelled_count]
})

print(invoice_counts.to_string(index=False))

 Invoice Type  Count
Cancelled (C)      0
Non-Cancelled 805620

# `Handling Duplicates Values`

In [ ]:
# Cek Duplicates
print("Jumlah duplicates sebelum cleaning:",df.duplicated().sum())

Jumlah duplicates sebelum cleaning: 26125

In [ ]:
# Drop Duplicates
df = df.drop_duplicates(keep="first")
print("Jumlah duplicates setelah cleaning:",df.duplicated().sum())

Jumlah duplicates setelah cleaning: 0

# `Cek Negatif Value`

In [ ]:
print("Negative value di kolom Quantity:",(df.Quantity<0).sum())
print("Negative value di kolom Price:",(df.Price<0).sum())

Negative value di kolom Quantity: 0
Negative value di kolom Price: 0

# Data Manipulation

In [ ]:
# Menambahkan kolom Total Harga
df['TotalPrice'] = df['Quantity'] * df['Price']

In [ ]:
# Konversi kolom tanggal ke format datetime
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])

In [ ]:
print("Max date :",df["InvoiceDate"].max())
print("Min date :",df["InvoiceDate"].min())

Max date : 2011-12-09 12:50:00
Min date : 2009-12-01 07:45:00

# Exploratory Data Analysis

In [ ]:
df.describe()

,Quantity,InvoiceDate,Price,Customer ID,TotalPrice
count,779495.000000,779495,779495.000000,779495.000000,779495.000000
mean,13.507085,2011-01-03 01:46:36.061116416,3.218199,15320.262918,22.289821
min,1.000000,2009-12-01 07:45:00,0.000000,12346.000000,0.000000
25%,2.000000,2010-07-02 14:39:00,1.250000,13971.000000,4.950000
50%,6.000000,2010-12-02 14:09:00,1.950000,15246.000000,12.480000
75%,12.000000,2011-08-01 13:48:00,3.750000,16794.000000,19.800000
max,80995.000000,2011-12-09 12:50:00,10953.500000,18287.000000,168469.600000
std,146.540284,NaN,29.674823,1695.722988,227.416962

In [ ]:
# Jumlah Customer di dataset
print("Jumlah Customer di dataset:", df["Customer ID"].nunique())

Jumlah Customer di dataset: 5881

In [ ]:
# Jumlah Invoice di dataset
print("Jumlah Invoice di dataset:", df["Invoice"].nunique())

Jumlah Invoice di dataset: 36975

In [ ]:
# Sum of product di dataset
print("Sum of product di dataset:", df["Quantity"].sum())

Sum of product di dataset: 10528705

In [ ]:
# Jumlah Harga Total di dataset
total_price_of_df = ((df["TotalPrice"].sum()).astype(int))
print("Jumlah Harga Total di dataset:", total_price_of_df)

Jumlah Harga Total di dataset: 17374804

In [ ]:
# Jumlah product di dataset
print("Jumlah product di dataset:", df["Description"].count())

Jumlah product di dataset: 779495

In [ ]:
# Urutan data dari Price tertinggi
df.sort_values(by = "Price", ascending  = False).head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,TotalPrice
135013,502263,M,Manual,1,2010-03-23 15:22:00,10953.50,12918.0,United Kingdom,10953.50
358639,524159,M,Manual,1,2010-09-27 16:12:00,10468.80,14063.0,United Kingdom,10468.80
74356,496115,M,Manual,1,2010-01-29 11:04:00,8985.60,17949.0,United Kingdom,8985.60
698843,551697,POST,POSTAGE,1,2011-05-03 13:46:00,8142.75,16029.0,United Kingdom,8142.75
129903,501766,M,Manual,1,2010-03-19 11:35:00,6958.17,15760.0,Norway,6958.17

In [ ]:
# Sorting data dari Price terendah
df.sort_values(by = "Price", ascending  = True).head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,TotalPrice
823515,562973,23157,SET OF 6 NATIVITY MAGNETS,240,2011-08-11 11:42:00,0.0,14911.0,EIRE,0.0
887286,568384,M,Manual,1,2011-09-27 09:46:00,0.0,12748.0,United Kingdom,0.0
89084,497819,TEST001,This is a test product.,5,2010-02-12 14:58:00,0.0,14103.0,United Kingdom,0.0
840209,564651,21786,POLKADOT RAIN HAT,144,2011-08-26 14:19:00,0.0,14646.0,Netherlands,0.0
945865,572893,21208,PASTEL COLOUR HONEYCOMB FAN,5,2011-10-26 14:36:00,0.0,18059.0,United Kingdom,0.0

In [ ]:
# Produk Terlaris
top_products = df.groupby('Description')['Quantity'].sum().sort_values(ascending=False).head(10)
print("10 PRODUK TERLARIS\n")
print(top_products)

10 PRODUK TERLARIS

Description
WORLD WAR 2 GLIDERS ASSTD DESIGNS     105185
WHITE HANGING HEART T-LIGHT HOLDER     91757
PAPER CRAFT , LITTLE BIRDIE            80995
ASSORTED COLOUR BIRD ORNAMENT          78234
MEDIUM CERAMIC TOP STORAGE JAR         77916
JUMBO BAG RED RETROSPOT                74224
BROCADE RING PURSE                     70082
PACK OF 60 PINK PAISLEY CAKE CASES     54592
60 TEATIME FAIRY CAKE CASES            52828
PACK OF 72 RETRO SPOT CAKE CASES       45129
Name: Quantity, dtype: int64

Simpan hasil Data Preprocessing untuk kemudian membuat dashboard di Power BI

In [ ]:
# Export ke Excel
df.to_excel('dataset_cleaned.xlsx', index=False)